# Example GitHub Actions Workflow for Java/Spring Boot Projects
# Place this at .github/workflows/code-review.yml in your Java project

name: AI Code Review - Java

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

permissions:
  contents: read
  pull-requests: write
  statuses: write
  checks: write

jobs:
  java-code-review:
    runs-on: ubuntu-latest
    name: Java Static Analysis & AI Review

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'  # or 'adopt', 'zulu', etc.
          cache: maven  # or 'gradle'

      # ==========================================
      # BUILD PROJECT
      # ==========================================

      - name: Build with Maven
        run: |
          mvn clean compile -DskipTests
        continue-on-error: false

      # Or for Gradle:
      # - name: Build with Gradle
      #   run: |
      #     ./gradlew clean compileJava -x test

      # ==========================================
      # FREE STATIC ANALYSIS TOOLS
      # ==========================================

      - name: Run SpotBugs
        run: mvn spotbugs:spotbugs
        continue-on-error: true

      - name: Run PMD
        run: mvn pmd:pmd pmd:cpd
        continue-on-error: true

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle
        continue-on-error: true

      # ==========================================
      # RUN TESTS WITH COVERAGE
      # ==========================================

      - name: Run Tests with JaCoCo Coverage
        run: mvn clean test jacoco:report
        continue-on-error: true

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: jacoco-report
          path: target/site/jacoco/

      # ==========================================
      # SECURITY SCANNING
      # ==========================================

      - name: Cache NVD Database
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: ${{ runner.os }}-nvd-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-nvd-

      - name: OWASP Dependency-Check
        run: mvn dependency-check:check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}  # Get free key from https://nvd.nist.gov/
        continue-on-error: true

      # ==========================================
      # ARCHITECTURE TESTING
      # ==========================================

      - name: Run ArchUnit Tests
        run: mvn test -Dtest=*ArchTest
        continue-on-error: true

      # ==========================================
      # OPTIONAL: PAID TOOLS INTEGRATION
      # ==========================================

      # Uncomment if you have SonarCloud
      # - name: SonarCloud Analysis
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.projectKey=your-org_your-project
      #       -Dsonar.organization=your-org

      # Uncomment if you have Qodana
      # - name: Qodana Scan
      #   uses: JetBrains/qodana-action@v2023.3
      #   with:
      #     linter: jetbrains/qodana-jvm:latest
      #   env:
      #     QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

      # Uncomment if you have Snyk
      # - name: Snyk Security Scan
      #   uses: snyk/actions/maven@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     command: test
      #   continue-on-error: true

      # ==========================================
      # COLLECT ANALYSIS REPORTS
      # ==========================================

      - name: Upload Analysis Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: static-analysis-reports
          path: |
            target/spotbugsXml.xml
            target/pmd.xml
            target/checkstyle-result.xml
            target/dependency-check-report.json
          retention-days: 30

      # ==========================================
      # AI CODE REVIEW (Main Integration)
      # ==========================================

      - name: Run AI Code Review
        uses: your-org/ai-review-cicd-actions/.github/workflows/reusable-ai-review.yml@main
        with:
          # Java-specific settings
          enable-java-analysis: true
          java-version: '17'

          # Configuration files
          config-file: '.github/ai-review-config.yml'
          company-config-url: 'github://your-org/policies/main/java-policies.yml'

          # Optional: Control which analyses run
          enable-python-analysis: false
          enable-js-analysis: false

        secrets:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          COMPANY_CONFIG_TOKEN: ${{ secrets.COMPANY_CONFIG_TOKEN }}

        permissions:
          contents: read
          pull-requests: write
          statuses: write

      # ==========================================
      # QUALITY GATES
      # ==========================================

      - name: Check Test Coverage
        run: |
          # Extract coverage percentage from JaCoCo report
          COVERAGE=$(grep -oPm1 "(?<=<counter type=\"LINE\" missed=\")[^\"]*" target/site/jacoco/jacoco.xml | head -1)
          echo "Line coverage: $COVERAGE"

          # Fail if coverage is below 80%
          if [ "$COVERAGE" -lt "80" ]; then
            echo "::error::Test coverage is below 80%"
            exit 1
          fi
        continue-on-error: true

      - name: Check Critical Vulnerabilities
        run: |
          # Check if critical vulnerabilities were found
          if [ -f target/dependency-check-report.json ]; then
            CRITICAL=$(jq '[.dependencies[].vulnerabilities[] | select(.severity=="CRITICAL")] | length' target/dependency-check-report.json)
            if [ "$CRITICAL" -gt "0" ]; then
              echo "::error::Found $CRITICAL critical vulnerabilities"
              exit 1
            fi
          fi
        continue-on-error: false

---

# Alternative: Minimal Setup (Just AI Review)
# If you want to use only the AI review system without running tools separately

name: AI Code Review - Minimal

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    uses: your-org/ai-review-cicd-actions/.github/workflows/reusable-ai-review.yml@main
    with:
      enable-java-analysis: true
      java-version: '17'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

---

# Alternative: Gradle-based Project

name: AI Code Review - Gradle

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  java-gradle-review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew clean compileJava

      - name: Run Static Analysis
        run: |
          ./gradlew spotbugsMain pmdMain checkstyleMain

      - name: Run Tests with Coverage
        run: ./gradlew test jacocoTestReport

      - name: OWASP Dependency Check
        run: ./gradlew dependencyCheckAnalyze
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      - name: AI Code Review
        uses: your-org/ai-review-cicd-actions/.github/workflows/reusable-ai-review.yml@main
        with:
          enable-java-analysis: true
          java-version: '17'
        secrets:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
