# Example: How to use the AI Code Review system in your project
# Place this file at .github/workflows/code-review.yml in your project

name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Use the reusable workflow from the central repository
jobs:
  code-review:
    uses: your-org/ai-review-cicd-actions/.github/workflows/reusable-ai-review.yml@main
    with:
      # Optional: Specify Python version (default: 3.11)
      python-version: '3.11'

      # Optional: Specify Node.js version (default: 20)
      node-version: '20'

      # Optional: Path to your project config (default: .github/ai-review-config.yml)
      config-file: '.github/ai-review-config.yml'

      # Optional: Company-level configuration URL
      company-config-url: 'github://your-org/policies/main/code-review-policies.yml'

      # Optional: Enable/disable language analysis
      enable-js-analysis: true
      enable-python-analysis: true

      # Optional: Fail workflow if review blocks PR (default: true)
      fail-on-blocking: true

    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Required if using Claude API directly
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      # Optional: Token for accessing private company config
      COMPANY_CONFIG_TOKEN: ${{ secrets.COMPANY_CONFIG_TOKEN }}

    permissions:
      contents: read
      pull-requests: write
      statuses: write
