# Self-Review Workflow
# This is the ACTUAL recommended pattern for using this review system
# Copy this to your project's .github/workflows/ai-review.yml

name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Prevent multiple runs on rapid pushes
concurrency:
  group: ai-review-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    name: AI-Driven Code Review
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better context

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11

      - name: Install Python dependencies
        run: uv sync

      - name: Install Claude Code CLI
        run: |
          curl -fsSL https://storage.googleapis.com/anthropic-files/claude-code/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          claude --version

      - name: Validate Environment
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          if [[ -z "$ANTHROPIC_API_KEY" ]]; then
            echo "::error::ANTHROPIC_API_KEY secret is not set"
            echo "::error::Add it in: Settings → Secrets → Actions → New secret"
            exit 1
          fi

          if [[ ! $ANTHROPIC_API_KEY =~ ^sk-ant- ]]; then
            echo "::error::Invalid ANTHROPIC_API_KEY format (should start with sk-ant-)"
            exit 1
          fi

          echo "Test" | claude --print "Say 'OK'" || {
            echo "::error::Claude Code authentication failed"
            exit 1
          }

          echo "✅ Environment validated"

      - name: Run AI Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-provided by GitHub Actions
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}  # Add to repo secrets
          CLAUDE_CODE_HEADLESS: '1'  # Disable interactive features
          NO_COLOR: '1'  # Disable ANSI colors
        run: |
          uv run python main.py \
            --repo ${{ github.repository }} \
            --pr ${{ github.event.pull_request.number }} \
            --config self/config.yml \
            --output review-results.json

      - name: Upload review results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: review-results-pr-${{ github.event.pull_request.number }}
          path: review-results.json
          retention-days: 30

      # Note: No need for manual result checking!
      # main.py already exits with code 1 if review blocks, 0 if passes
      # GitHub Actions automatically fails the workflow on non-zero exit code
