# Local Pattern: Python Project Self-Review
# Copy this AI review system into your project and run it locally

name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ai-review-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync

      - name: Install Claude Code CLI
        run: |
          curl -fsSL https://storage.googleapis.com/anthropic-files/claude-code/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          claude --version

      - name: Validate Environment
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          if [[ -z "$ANTHROPIC_API_KEY" ]]; then
            echo "::error::ANTHROPIC_API_KEY not set"
            exit 1
          fi
          echo "Test" | claude --print "Say 'OK'" || exit 1

      - name: Run AI Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          CLAUDE_CODE_HEADLESS: '1'
          NO_COLOR: '1'
        run: |
          uv run python main.py \
            --repo ${{ github.repository }} \
            --pr ${{ github.event.pull_request.number }} \
            --config .github/ai-review-config.yml \
            --output review-results.json

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: review-results-pr-${{ github.event.pull_request.number }}
          path: review-results.json
          retention-days: 30
